spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    generate-dll: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/book_db
    username: book
    password: book
  hikari:
    schema: book_schema
    connection-init-sql: CREATE SCHEMA IF NOT EXISTS book_schema
    connection-timeout: 10000


book:
  redis:
    enable: true
  cache:
    cache_names:
      - bookByNameOrAuthor
      - booksByCategories
    caches:
      bookByNameOrAuthor:
        expiry: 10m
      booksByCategories:
        expiry: 10m